export { default as calcDryMinutes } from './calcDryMinutes'
export { default as createElement } from './createElement'
export { default as getCoords } from './getCoords'
export { default as getData } from './getData'
export { default as getCity } from './getCity'
export { default as removeChildren } from './removeChildren'
export { default as renderOutcome } from './renderOutcome'
