export { default as header } from './globals/header'
export { default as footer } from './globals/footer'
export { default as load } from './globals/load'
export { default as homeScreen } from './screens/homeScreen'
export { default as countriesScreen } from './screens/countriesScreen'
export { default as detailScreen } from './screens/detailScreen'
export { default as fourOfourScreen } from './screens/fourOfourScreen'
